//
//  EventDataTests.swift
//  swift-kurrentdb
//

import Foundation
import Testing
@testable import KurrentDB

@Suite("EventData Tests")
struct EventDataTests {

    // MARK: - ID Generation

    @Test("Auto-generated IDs are unique across instances")
    func testAutoGeneratedIDsAreUnique() {
        let e1 = EventData(eventType: "Foo", data: Data(), contentType: .json)
        let e2 = EventData(eventType: "Foo", data: Data(), contentType: .json)
        #expect(e1.id != e2.id)
    }

    @Test("Custom UUID is preserved")
    func testCustomIDIsPreserved() {
        let id = UUID()
        let event = EventData(id: id, eventType: "Foo", data: Data(), contentType: .json)
        #expect(event.id == id)
    }

    // MARK: - Event Type

    @Test("Event type is stored correctly")
    func testEventTypeIsStored() {
        let event = EventData(eventType: "OrderPlaced", data: Data(), contentType: .json)
        #expect(event.eventType == "OrderPlaced")
    }

    @Test("Metadata dictionary contains event type under 'type' key")
    func testMetadataContainsEventType() {
        let event = EventData(eventType: "AccountCreated", data: Data(), contentType: .json)
        #expect(event.metadata["type"] == "AccountCreated")
    }

    // MARK: - Payload and ContentType

    @Test("JSON model payload has content-type .json")
    func testJSONModelContentType() {
        struct Order: Codable, Sendable { let id: Int }
        let event = EventData(eventType: "OrderPlaced", model: Order(id: 42))
        #expect(event.payload.contentType == .json)
    }

    @Test("Binary data payload has content-type .binary")
    func testBinaryContentType() {
        let event = EventData(eventType: "Blob", data: Data([0x01, 0x02]), contentType: .binary)
        #expect(event.payload.contentType == .binary)
    }

    @Test("Metadata contains correct content-type for JSON")
    func testMetadataContentTypeJSON() {
        let event = EventData(eventType: "Foo", data: Data(), contentType: .json)
        #expect(event.metadata["content-type"] == ContentType.json.rawValue)
    }

    @Test("Metadata contains correct content-type for binary")
    func testMetadataContentTypeBinary() {
        let event = EventData(eventType: "Foo", data: Data(), contentType: .binary)
        #expect(event.metadata["content-type"] == ContentType.binary.rawValue)
    }

    @Test("JSON model payload encodes to non-empty data")
    func testJSONPayloadEncodesData() throws {
        struct Payload: Codable, Sendable { let value: String }
        let event = EventData(eventType: "Test", model: Payload(value: "hello"))
        let data = try event.payload.data
        #expect(!data.isEmpty)
    }

    // MARK: - Bytes initializer

    @Test("Bytes initializer matches equivalent Data initializer")
    func testBytesInitMatchesDataInit() {
        let bytes: [UInt8] = [1, 2, 3]
        let fromBytes = EventData(eventType: "Bytes", bytes: bytes, contentType: .binary)
        let fromData  = EventData(eventType: "Bytes", data: Data(bytes), contentType: .binary)
        #expect(fromBytes.eventType == fromData.eventType)
        #expect(fromBytes.payload.contentType == fromData.payload.contentType)
    }

    // MARK: - Custom metadata

    @Test("Custom metadata is stored and retrievable")
    func testCustomMetadataIsStored() {
        let meta = "custom-payload".data(using: .utf8)!
        let event = EventData(eventType: "Foo", data: Data(), contentType: .json, customMetadata: meta)
        #expect(event.customMetadata == meta)
    }

    @Test("Nil custom metadata is stored as nil")
    func testNilCustomMetadata() {
        let event = EventData(eventType: "Foo", data: Data(), contentType: .json, customMetadata: nil)
        #expect(event.customMetadata == nil)
    }
}
