#!/usr/bin/env python3
"""Extract the Swift code blocks from the documentation so the compiler can check them.

Every ```swift block in the DocC catalog, README.md, and the `///` doc comments of the
public library sources becomes the body of its own
`async throws` function in `Tests/DocSnippetsTests/DocSnippets.generated.swift`.
Building the `DocSnippetsTests` target then fails whenever a documented example no
longer matches the API. `#sourceLocation` points compiler errors back at the Markdown.

Names the examples use without declaring them (`client`, `settings`, ...) come from
`Tests/DocSnippetsTests/Prelude.swift`.

Directives, written as an HTML comment on the line directly above a code fence
(DocC and GitHub both hide HTML comments):

    <!-- snippet:skip -->      don't compile this block (1.x code, deliberate errors)
    <!-- snippet:continue -->  append this block to the previous one in the same file,
                               so it can use the names that block declared
    <!-- snippet:toplevel -->  declare the block's types and functions alongside the file's
                               snippets instead of inside one (each Markdown file gets its
                               own namespace, so names don't collide across files)

Usage: python3 scripts/generate-doc-snippets.py
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCES = (
    sorted((ROOT / "Sources/KurrentDB/KurrentDB.docc").rglob("*.md"))
    + [ROOT / "README.md"]
    + sorted((ROOT / "Sources/KurrentDB").rglob("*.swift"))
    + sorted((ROOT / "Sources/KurrentDBPool").rglob("*.swift"))
)
OUTPUT = ROOT / "Tests/DocSnippetsTests/DocSnippets.generated.swift"

FENCE_OPEN = re.compile(r"^(\s*)```swift\s*$")
FENCE_CLOSE = re.compile(r"^\s*```\s*$")
DIRECTIVE = re.compile(r"^\s*<!--\s*snippet:(skip|continue|toplevel)\s*-->\s*$")
DOC_COMMENT = re.compile(r"^\s*/// ?(.*)$")
IMPORT = re.compile(r"^\s*import\s+\w+\s*$")
# Free functions and globals in a toplevel block become static members of the namespace.
FREE_DECLARATION = re.compile(r"^(func|let|var) ")


def extract(path):
    """Yield (directive, first_line_number, lines) for each swift block in `path`."""
    lines = path.read_text(encoding="utf-8").splitlines()
    if path.suffix == ".swift":
        # Keep only doc-comment text; blank out code so line numbers still match.
        lines = [m.group(1) if (m := DOC_COMMENT.match(l)) else "" for l in lines]
    i = 0
    while i < len(lines):
        opened = FENCE_OPEN.match(lines[i])
        if not opened:
            i += 1
            continue
        directive = None
        j = i - 1
        while j >= 0 and not lines[j].strip():
            j -= 1
        if j >= 0 and (m := DIRECTIVE.match(lines[j])):
            directive = m.group(1)
        indent = len(opened.group(1))
        start = i + 1
        i += 1
        body = []
        while i < len(lines) and not FENCE_CLOSE.match(lines[i]):
            body.append(lines[i][indent:] if lines[i][:indent].isspace() else lines[i])
            i += 1
        if i == len(lines):
            sys.exit(f"{path.relative_to(ROOT)}:{start}: unterminated ```swift block")
        yield directive, start + 1, body
        i += 1


def location(path, line):
    # Absolute, so diagnostics resolve no matter which directory the compiler runs in.
    return f'#sourceLocation(file: "{path}", line: {line})'


def main():
    out = [
        "// Generated by scripts/generate-doc-snippets.py — do not edit.",
        "import Foundation",
        "import KurrentDB",
        "import KurrentDBPool",
        "",
    ]
    count = 0
    for path in SOURCES:
        # Each Markdown file gets its own namespace, so type names declared in one
        # article don't collide with the same names in another.
        namespace = "Doc_" + re.sub(r"\W+", "_", str(path.relative_to(ROOT).with_suffix("")))
        toplevel, functions, current = [], [], None
        for index, (directive, line, body) in enumerate(extract(path)):
            if directive == "skip":
                continue
            code = [location(path, line)] + ["" if IMPORT.match(l) else l for l in body]
            if directive == "toplevel":
                code = [FREE_DECLARATION.sub(r"static \1 ", l) for l in code]
                toplevel.extend(code + ["#sourceLocation()"])
                current = None
            elif directive == "continue" and current is not None:
                current.extend(code)
            else:
                current = [f"static func snippet{index}() async throws {{"] + code
                functions.append(current)
        if not toplevel and not functions:
            continue
        count += len(functions)
        out.append(f"enum {namespace} {{")
        out += toplevel
        for function in functions:
            out += function + ["#sourceLocation()", "}"]
        out += ["}", ""]
    OUTPUT.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {count} snippets to {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
